-- Importación de pacientes hospitalizados - Sismo Venezuela 2026
-- Tabla de staging en PostgreSQL. Campos no presentes en la fuente: NULL.
-- Fuente cruzada: data 2.docx y data 3.docx; data 1.pdf coincide como versión renderizada/maestra de la misma data.
-- Total final sin duplicados automáticos: 313 pacientes.

BEGIN;

CREATE TABLE IF NOT EXISTS public.pacientes_importacion_sismo (
  id BIGSERIAL PRIMARY KEY,
  nombre_completo VARCHAR(50) NOT NULL,
  cedula_tipo VARCHAR(1) NULL,
  cedula VARCHAR(9) NULL,
  telefono_contacto VARCHAR(15) NULL,
  edad INTEGER NULL CHECK (edad IS NULL OR (edad >= 0 AND edad <= 120)),
  estado VARCHAR(100) NULL,
  municipio VARCHAR(100) NULL,
  parroquia VARCHAR(100) NULL,
  foto_paciente TEXT NULL,
  ubicacion_especifica TEXT NULL,
  estado_salud VARCHAR(100) NULL,
  direccion_referencial TEXT NULL,
  observaciones TEXT NULL,
  fuente TEXT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pacientes_importacion_sismo_nombre ON public.pacientes_importacion_sismo (nombre_completo);
CREATE INDEX IF NOT EXISTS idx_pacientes_importacion_sismo_cedula ON public.pacientes_importacion_sismo (cedula);
CREATE INDEX IF NOT EXISTS idx_pacientes_importacion_sismo_ubicacion ON public.pacientes_importacion_sismo (ubicacion_especifica);

INSERT INTO public.pacientes_importacion_sismo (
  nombre_completo, cedula_tipo, cedula, telefono_contacto, edad, estado, municipio, parroquia, foto_paciente, ubicacion_especifica, estado_salud, direccion_referencial, observaciones, fuente
) VALUES
  ('IBARRA ANA', NULL, NULL, NULL, 74, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('TORREALBA NUVIA', NULL, NULL, NULL, 68, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('GARCIA YENNY', NULL, NULL, NULL, 34, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('ISCALA YENNY', NULL, NULL, NULL, 42, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('ABREU PAULINA', NULL, NULL, NULL, 8, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('TRUJILLO ELIAN', NULL, NULL, NULL, 19, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('LISCANO PEDRO', NULL, NULL, NULL, 40, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('MARCANO KATIUSKA', NULL, NULL, NULL, 56, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('ARRIETA DORIS', NULL, NULL, NULL, 65, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('BALBUENO WILMED', NULL, NULL, NULL, 37, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('WINCHESTER KELLYS', NULL, NULL, NULL, 28, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('VEGA SAMUEL', NULL, NULL, NULL, 11, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('RONDÓN ANGEL', NULL, NULL, NULL, 12, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('RENGIFO GUILLERMINA', NULL, NULL, NULL, 46, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('GONZALEZ OLGA', NULL, NULL, NULL, 63, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('MIJARES ISOLIBETH', NULL, NULL, NULL, 45, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('URBINA SILIBETO', NULL, NULL, NULL, 80, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('BORGES LILIANE', NULL, NULL, NULL, 21, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('ALAYON SUHYN', NULL, NULL, NULL, 25, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('BISVAL CLARA', NULL, NULL, NULL, 62, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('RIVAS FRANKENIL', NULL, NULL, NULL, 53, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('PORTILLO OMAR', NULL, NULL, NULL, 40, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('SUAREZ RENE', NULL, NULL, NULL, 62, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('CALDERA LEWIS', NULL, NULL, NULL, 40, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('PADILLA RODOSKI', NULL, NULL, NULL, 4, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('RAMÍREZ MARIANGEL', NULL, NULL, NULL, 33, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('BLANCOS YESSICA', NULL, NULL, NULL, 53, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('RIVAS FABINA', NULL, NULL, NULL, 23, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('MILANO GLADIVSKA', NULL, NULL, NULL, 29, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('MUÑON MARIANGEL', NULL, NULL, NULL, 59, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('VASCONCELO ANDREINA', NULL, NULL, NULL, 43, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('PADILLA RODOSKI', NULL, NULL, NULL, 52, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('PIRETO SEBASTIÁN', NULL, NULL, NULL, 16, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('BARRETO RICARDO', NULL, NULL, NULL, 42, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('OBREGON DIEGO', NULL, NULL, NULL, 14, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('CABEZA KARINA', NULL, NULL, NULL, 30, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('GONZALEZ ALEXANDRA', NULL, NULL, NULL, 42, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('CHACÓN CARLOS', NULL, NULL, NULL, 43, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('LOPEZ HADDY F', NULL, NULL, NULL, 42, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('CASTILLO VICTORIA', NULL, NULL, NULL, 40, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('CASTAÑO DANA', NULL, NULL, NULL, 17, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('TORRES MILAGROS', NULL, NULL, NULL, 46, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('PARRA GABRIELA', NULL, NULL, NULL, 19, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('ARTEAGA GLADYS', NULL, NULL, NULL, 72, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('VILCHEZ BRAYAN', NULL, NULL, NULL, 23, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('FUENTES ALBERTO', NULL, NULL, NULL, 52, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('PEREZ FRANCISCA', NULL, NULL, NULL, 63, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('MARABITO JOSEANI', NULL, NULL, NULL, 32, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('ABELLO MATILDE', NULL, NULL, NULL, 36, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, 'Fallecida', 'data 2.docx;data 3.docx'),
  ('RODRIGUEZ EDUARDO', NULL, NULL, NULL, 65, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('DIVITO ROSA', NULL, NULL, NULL, 64, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('GUERRERO DEIVERSON', NULL, NULL, NULL, 20, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('CÓRDOVA ARNALDO', NULL, NULL, NULL, 19, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, 'Qx', 'data 2.docx;data 3.docx'),
  ('REY JENNICEL', NULL, NULL, NULL, 29, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('RIVERO DANIEL', NULL, NULL, NULL, 60, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('BLANCO JOSE', NULL, NULL, NULL, 6, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('FERNANDEZ NEISY', NULL, NULL, NULL, 37, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('ROJAS RAFAEL', NULL, NULL, NULL, 50, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('GONZALEZ STEPHANY', NULL, NULL, NULL, 22, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('GONZALEZ RAFAEL', NULL, NULL, NULL, 39, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('CASTRO JUAN', NULL, NULL, NULL, 26, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('ESCALONA IVIS', NULL, NULL, NULL, 55, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('SERRANO NANCY', NULL, NULL, NULL, 67, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('ROMERO JOSE', NULL, NULL, NULL, 60, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('GUAVINI EFREN P.2', NULL, NULL, NULL, 30, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('CISNERO ROSA', NULL, NULL, NULL, 57, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('MUÑOZ JOSEFINA', NULL, NULL, NULL, 72, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('ACOSTA ISAEL', NULL, NULL, NULL, 10, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('ACOSTA ALEXANDER', NULL, NULL, NULL, 47, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('ACOSTA HASAEL', NULL, NULL, NULL, 13, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('BETANCOURT MARIA', NULL, NULL, NULL, 74, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, 'Fallecida', 'data 2.docx;data 3.docx'),
  ('IZQUIERDO IRAIMA', NULL, NULL, NULL, 83, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, 'Fallecida', 'data 2.docx;data 3.docx'),
  ('VASQUE LUIS', NULL, NULL, NULL, 77, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, 'Fallecida', 'data 2.docx;data 3.docx'),
  ('ALBE MANUEL', NULL, NULL, NULL, 77, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('GONZALEZ ALBIMAR', NULL, NULL, NULL, 59, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('FERNANDEZ EFRAIN', NULL, NULL, NULL, 31, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('MENDEZ YESIRE', NULL, NULL, NULL, 24, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('PARRA ESTEFANÍA', NULL, NULL, NULL, 15, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('DELGADO EDIMAR', NULL, NULL, NULL, 23, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('OLDAZ LUISANA', NULL, NULL, NULL, 58, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('MACHADO ANARELLA', NULL, NULL, NULL, 9, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('FRONTADO MIEL', NULL, NULL, NULL, 7, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('SIMENEZ AXIEL', NULL, NULL, NULL, 4, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, 'Qx', 'data 2.docx;data 3.docx'),
  ('PEDRON JESÚS', NULL, NULL, NULL, 68, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('GOYO RAFAEL', NULL, NULL, NULL, 32, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('OMASIENTO SEBASTIÁN', NULL, NULL, NULL, 16, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('BLANCO CARMEN', NULL, NULL, NULL, 55, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('CABARCA VENDEZILÍN', NULL, NULL, NULL, 13, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, 'Qx', 'data 2.docx;data 3.docx'),
  ('SEQUELA SOFIA', NULL, NULL, NULL, 19, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('SALAZAR ARTURO', NULL, NULL, NULL, 43, NULL, NULL, NULL, NULL, 'Hospital Domingo Luciani', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('OROZCO YUSBELIS', NULL, '24140952', '0412-9970844', 35, NULL, NULL, NULL, NULL, 'Hospital Universitario de Caracas', NULL, 'SANTA ROSALIA', NULL, 'data 2.docx;data 3.docx'),
  ('CUYAN FRAN', NULL, '10235290', '0424-2927910', 60, NULL, NULL, NULL, NULL, 'Hospital Universitario de Caracas', NULL, 'LA FLORIDA', NULL, 'data 2.docx;data 3.docx'),
  ('OJEDA CARLOS', NULL, '12066889', '0424-4437142', 51, NULL, NULL, NULL, NULL, 'Hospital Universitario de Caracas', NULL, 'SANTA ROSA', NULL, 'data 2.docx;data 3.docx'),
  ('RAMIREZ YILMAR', NULL, '22316562', '0424-5364882', 32, NULL, NULL, NULL, NULL, 'Hospital Universitario de Caracas', NULL, 'PLAZA VENEZUELA', NULL, 'data 2.docx;data 3.docx'),
  ('MOYANO JAIME', NULL, '26346743', '0426-3844124', 28, NULL, NULL, NULL, NULL, 'Hospital Universitario de Caracas', NULL, 'MARICHE', NULL, 'data 2.docx;data 3.docx'),
  ('BENEDETI YORLIANIS', NULL, '25846221', '0424-1737018', 29, NULL, NULL, NULL, NULL, 'Hospital Universitario de Caracas', NULL, 'ALTAMIRA', NULL, 'data 2.docx;data 3.docx'),
  ('TRIGOSO CARLOS', NULL, '8418724', '0412-1290170', 59, NULL, NULL, NULL, NULL, 'Hospital Universitario de Caracas', NULL, 'LA VEGA', NULL, 'data 2.docx;data 3.docx'),
  ('MARRERO YORGELIS', NULL, '31331652', '0414-0209230', 20, NULL, NULL, NULL, NULL, 'Hospital Universitario de Caracas', NULL, 'PARACOTO', NULL, 'data 2.docx;data 3.docx'),
  ('TOVAR LUISONA', NULL, '17443980', '0412-6392426', 17, NULL, NULL, NULL, NULL, 'Hospital Universitario de Caracas', NULL, 'EL VALLE', NULL, 'data 2.docx;data 3.docx'),
  ('CARILLO YASMIN', NULL, '5424760', '0412-1825267', 67, NULL, NULL, NULL, NULL, 'Hospital Universitario de Caracas', NULL, 'LOS ROSALES', NULL, 'data 2.docx;data 3.docx'),
  ('NOGUERA FABIAN', NULL, '30334636', '0424-2850105', 22, NULL, NULL, NULL, NULL, 'Hospital Universitario de Caracas', NULL, 'PINTO SALINAS', NULL, 'data 2.docx;data 3.docx'),
  ('CASTELLANO JOSE', NULL, '21364204', '0424-2738577', 35, NULL, NULL, NULL, NULL, 'Hospital Universitario de Caracas', NULL, 'PRIVADOS DE LIBERTAD', NULL, 'data 2.docx;data 3.docx'),
  ('BARAJA ANDRES', NULL, '17491087', '0424-2738577', 41, NULL, NULL, NULL, NULL, 'Hospital Universitario de Caracas', NULL, 'PRIVADOS DE LIBERTAD', NULL, 'data 2.docx;data 3.docx'),
  ('SANDOVAL DORIS', NULL, '4029093', '0424-2577096', 80, NULL, NULL, NULL, NULL, 'Hospital Universitario de Caracas', NULL, 'AVENIDA LECUNA', NULL, 'data 2.docx;data 3.docx'),
  ('ESCALONA JOAQUIN', NULL, '6482918', '0414-9081729', 65, NULL, NULL, NULL, NULL, 'Hospital Universitario de Caracas', NULL, 'EL VALLE', NULL, 'data 2.docx;data 3.docx'),
  ('SOSA EMILIA', NULL, '3409148', '0414-3367038', 78, NULL, NULL, NULL, NULL, 'Hospital Universitario de Caracas', NULL, 'AV VICTORIA', NULL, 'data 2.docx;data 3.docx'),
  ('SANCHEZ JOSE', NULL, '32320251', '0412-3574177', 19, NULL, NULL, NULL, NULL, 'Hospital Universitario de Caracas', NULL, 'LOS TEQUES', NULL, 'data 2.docx;data 3.docx'),
  ('LOPEZ FRANCISCA', NULL, '33230043', '0424-2414874', 16, NULL, NULL, NULL, NULL, 'Hospital Universitario de Caracas', NULL, 'SAN AGUSTIN', NULL, 'data 2.docx;data 3.docx'),
  ('MENDOZA ANA', NULL, '5343446', '0424-1519166', 72, NULL, NULL, NULL, NULL, 'Hospital Universitario de Caracas', NULL, 'PINTO SALINAS', NULL, 'data 2.docx;data 3.docx'),
  ('ANTEQUIA MAYULI', NULL, '12882457', '0424-5860106', 50, NULL, NULL, NULL, NULL, 'Hospital Universitario de Caracas', NULL, 'CACIQUE TIUNA', NULL, 'data 2.docx;data 3.docx'),
  ('URBINA MOISES', NULL, '22513789', '0412-9854079', 30, NULL, NULL, NULL, NULL, 'Hospital Universitario de Caracas', NULL, 'MONTALBAN', 'Teléfono alternativo en fuente: 0424-3357891', 'data 2.docx;data 3.docx'),
  ('MONTILLA NANCY', NULL, '10813576', '0414-1878802', 57, NULL, NULL, NULL, NULL, 'Hospital Universitario de Caracas', NULL, 'CEMENTERIO', NULL, 'data 2.docx;data 3.docx'),
  ('ZAMBRANO DOMINI', NULL, '18274233', '0412-2913570', 39, NULL, NULL, NULL, NULL, 'Hospital Universitario de Caracas', NULL, 'CATIA', NULL, 'data 2.docx;data 3.docx'),
  ('PALACIO JHON', NULL, '25304211', '0412-5749550', 31, NULL, NULL, NULL, NULL, 'Hospital Universitario de Caracas', NULL, 'COCHE', NULL, 'data 2.docx;data 3.docx'),
  ('CORTEZ NOELI', NULL, '22538576', '0424-2562305', 30, NULL, NULL, NULL, NULL, 'Hospital Universitario de Caracas', NULL, 'LAS MAYAS', NULL, 'data 2.docx;data 3.docx'),
  ('PANTOJA RAINER', NULL, '36085467', '0424-2562305', 17, NULL, NULL, NULL, NULL, 'Hospital Universitario de Caracas', NULL, 'LAS MAYAS', NULL, 'data 2.docx;data 3.docx'),
  ('DANTOJA TONI', NULL, '13409559', '0424-2562305', 47, NULL, NULL, NULL, NULL, 'Hospital Universitario de Caracas', NULL, 'LAS MAYAS', NULL, 'data 2.docx;data 3.docx'),
  ('HANMA ANTONIO', NULL, '5072832', '0424-2183524', 66, NULL, NULL, NULL, NULL, 'Hospital Universitario de Caracas', NULL, 'AV PASCUAL', NULL, 'data 2.docx;data 3.docx'),
  ('MORALES MARIA', NULL, '32807709', NULL, 18, NULL, NULL, NULL, NULL, 'Hospital Universitario de Caracas', NULL, 'LA GUAIRA EL TREBOL', NULL, 'data 2.docx;data 3.docx'),
  ('COA DEIVIS', NULL, '18780841', '0424-1534022', 36, NULL, NULL, NULL, NULL, 'Hospital Universitario de Caracas', NULL, 'LA GUAIRA', NULL, 'data 2.docx;data 3.docx'),
  ('RUEDA JOSE', NULL, '15430608', '0416-7089152', 45, NULL, NULL, NULL, NULL, 'Hospital Universitario de Caracas', NULL, 'AV LIBERTADOR', NULL, 'data 2.docx;data 3.docx'),
  ('ROSIER LIZ', NULL, '26068002', '0412-9095086', 28, NULL, NULL, NULL, NULL, 'Hospital Universitario de Caracas', NULL, 'LA GUAIRA', NULL, 'data 2.docx;data 3.docx'),
  ('OJEDA YONTACO', NULL, '13470155', '0424-8168787', 62, NULL, NULL, NULL, NULL, 'Hospital Universitario de Caracas', NULL, 'EL VALLE COCHE', NULL, 'data 2.docx;data 3.docx'),
  ('MUÑOZ GEMA', NULL, '27797121', '0416-7537984', 24, NULL, NULL, NULL, NULL, 'Hospital Universitario de Caracas', NULL, 'EL VALLE', NULL, 'data 2.docx;data 3.docx'),
  ('ACOSTA YOLERFAN', NULL, '28136168', '0412-3475759', 26, NULL, NULL, NULL, NULL, 'Hospital Universitario de Caracas', NULL, 'LA GUAIRA', NULL, 'data 2.docx;data 3.docx'),
  ('RODRIGUEZ MAIKEL', NULL, '16208203', '0412-2091099', 42, NULL, NULL, NULL, NULL, 'Hospital Universitario de Caracas', NULL, 'COCHE', NULL, 'data 2.docx;data 3.docx'),
  ('SOMOZA RIAND', NULL, '15267293', '0412-2983051', 19, NULL, NULL, NULL, NULL, 'Hospital Universitario de Caracas', NULL, 'EL VALLE', NULL, 'data 2.docx;data 3.docx'),
  ('SOLORZANO OMARÑO', NULL, '31445070', '0412-3175785', 18, NULL, NULL, NULL, NULL, 'Hospital Universitario de Caracas', NULL, 'LA GUAIRA', NULL, 'data 2.docx;data 3.docx'),
  ('LA VERDE VICTOR', NULL, '30334452', '0412-8162456', 18, NULL, NULL, NULL, NULL, 'Hospital Universitario de Caracas', NULL, 'LA GUAIRA', NULL, 'data 2.docx;data 3.docx'),
  ('LU DINGPI', NULL, '8358411', '0424-3579081', 49, NULL, NULL, NULL, NULL, 'Hospital Universitario de Caracas', NULL, 'LA GUAIRA', NULL, 'data 2.docx;data 3.docx'),
  ('WU HUA JUAN', NULL, '8229616', '0412-3958541', 47, NULL, NULL, NULL, NULL, 'Hospital Universitario de Caracas', NULL, 'LA GUAIRA', NULL, 'data 2.docx;data 3.docx'),
  ('WU SUSUP', NULL, '34553337', '0412-3758541', 14, NULL, NULL, NULL, NULL, 'Hospital Universitario de Caracas', NULL, 'LA GUAIRA', NULL, 'data 2.docx;data 3.docx'),
  ('CÁCERES NATHALIA', NULL, '36192938', '0424-1507138', 13, NULL, NULL, NULL, NULL, 'Hospital Universitario de Caracas', NULL, 'LA GUAIRA', NULL, 'data 2.docx;data 3.docx'),
  ('CÁCERES PATRICIA', NULL, '32790475', '0424-1507138', 18, NULL, NULL, NULL, NULL, 'Hospital Universitario de Caracas', NULL, 'LA GUAIRA', NULL, 'data 2.docx;data 3.docx'),
  ('CÁCERES ELIOSE', NULL, '11061197', '0426-1507138', 55, NULL, NULL, NULL, NULL, 'Hospital Universitario de Caracas', NULL, 'LA GUAIRA', NULL, 'data 2.docx;data 3.docx'),
  ('PEREZ ARIANI', NULL, '24175821', '0414-7335723', 20, NULL, NULL, NULL, NULL, 'Hospital Universitario de Caracas', NULL, 'LA GUAIRA', NULL, 'data 2.docx;data 3.docx'),
  ('IBARRA WUIKMER/WILMER', NULL, '15332705', '0412-9646938', 45, NULL, NULL, NULL, NULL, 'Hospital Universitario de Caracas', NULL, 'LA GUAIRA', NULL, 'data 2.docx;data 3.docx'),
  ('LÓPEZ EDIS', NULL, '6045544', '0412-2928549', 70, NULL, NULL, NULL, NULL, 'Hospital Universitario de Caracas', NULL, 'CATIA TAMARINDO / LA GUAIRA', NULL, 'data 2.docx;data 3.docx'),
  ('OROPEZA SOCORRO', NULL, '11639518', '0412-2728549', 53, NULL, NULL, NULL, NULL, 'Hospital Universitario de Caracas', NULL, 'LA GUAIRA', NULL, 'data 2.docx;data 3.docx'),
  ('OROPEZA CATIA', NULL, '11639511', NULL, 52, NULL, NULL, NULL, NULL, 'Hospital Universitario de Caracas', NULL, 'LA GUAIRA', NULL, 'data 2.docx;data 3.docx'),
  ('GOSLING HAIRMON', NULL, '29900166', '0414-5215646', 49, NULL, NULL, NULL, NULL, 'Hospital Universitario de Caracas', NULL, 'La Guaira', 'Nombre alternativo en fuente: GOSLING RAYMOND | Teléfono alternativo en fuente: 0412-2520602', 'data 2.docx;data 3.docx'),
  ('ABREU JOSE', NULL, '15810058', NULL, 52, NULL, NULL, NULL, NULL, 'Hospital Universitario de Caracas', NULL, 'Hoyo de la Puerta', NULL, 'data 2.docx;data 3.docx'),
  ('SILVA IBRAHIM', NULL, '20562844', NULL, 35, NULL, NULL, NULL, NULL, 'Hospital Universitario de Caracas', NULL, 'CATIA LA MAR', NULL, 'data 2.docx;data 3.docx'),
  ('MENDOZA MARIO', NULL, '6274191', NULL, 73, NULL, NULL, NULL, NULL, 'Hospital Universitario de Caracas', NULL, 'LA GUAIRA', NULL, 'data 2.docx;data 3.docx'),
  ('RAMOS/SILVA MARYELIS', NULL, '32111741', NULL, 18, NULL, NULL, NULL, NULL, 'Hospital Universitario de Caracas', NULL, 'Los Caracas / La Guaira', NULL, 'data 2.docx;data 3.docx'),
  ('SILVA INDIANA', NULL, '14929760', '0412-0109465', 46, NULL, NULL, NULL, NULL, 'Hospital Universitario de Caracas', NULL, 'LA GUAIRA', NULL, 'data 2.docx;data 3.docx'),
  ('GUZMAN ANGELICA', NULL, '13717596', '0424-2668717', 48, NULL, NULL, NULL, NULL, 'Hospital Universitario de Caracas', NULL, 'LA GUAIRA', NULL, 'data 2.docx;data 3.docx'),
  ('MARCANO ROSA', NULL, '41498435', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('SANDOVAL ADRIANA', NULL, '34518879', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('MIRANDA VICTORIA', NULL, '34054588', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('GUTIERREZ JOSE', NULL, '28447519', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('ORANA EDUAR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('GONZALEZ MILEIBIS', NULL, '26468240', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('SEDEÑO MARYURI', NULL, '14194021', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('RAMIREZ HEILIMAR', NULL, '32543420', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('BRIZUELA GABRIEL', NULL, '32781459', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('CARRIZO VIVIANA', NULL, '33232603', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('GARCIA DIEGO', NULL, '33423811', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('LEON GONZALO', NULL, '22916224', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('MIJARES CELIANA', NULL, '19734177', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('ORTUÑO YENNY', NULL, '5199652', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, 'Nombre alternativo en fuente: ORTUÑO YONI', 'data 2.docx;data 3.docx'),
  ('PACHECO CESAR', NULL, '26327366', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('DIAS ANA', NULL, '10576803', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('URDIDAS ADRIANA', NULL, '17856045', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('AGUILERA ANA', NULL, '20003134', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('ALVAREZ WILLIAN', NULL, '16125101', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('CARDENAS ALEXANDRA', NULL, '28143770', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('SUCRE FRANCIS MEDINA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, '18 años', 'data 2.docx;data 3.docx'),
  ('HERNANDEZ CRUZ', NULL, '4636722', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('RONDON FRAN', NULL, '19659867', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('BECERRA LEONARDO', NULL, '34800366', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('RAMIREZ ORIANA', NULL, '27006264', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('VIERA YULID PAREDES', NULL, '3883421', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, 'Nombre alternativo en fuente: PAREDES YULID', 'data 2.docx;data 3.docx'),
  ('CORDERO YADIRA', NULL, '12763837', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('RONDON DAYANA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, '18 años', 'data 2.docx;data 3.docx'),
  ('QUINTERO CRISDALIS', NULL, '32865296', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('GODOY ERIC', NULL, '18749225', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('MOLINA NAGIBI', NULL, '29768360', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('ECHARA MARIA', NULL, '27044236', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('GOMEZ MANUEL', NULL, '18814839', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('CASTILLO AYARI', NULL, '26327913', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('MEDINA NATHACHA', NULL, '29565365', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('IGLESIAS IHSEN', NULL, '32359883', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('VALERO MARIA FELICIA', NULL, '13374764', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('GUILLEN MARIA', NULL, '6059288', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('GARCIA JUVYER', NULL, '27377514', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('GRANADO CRISBEL', NULL, '23926261', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('MARTINEZ WILLIAMS', NULL, '19367804', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('LOPEZ NATIN', NULL, '15541666', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('LOPEZ THAIS', NULL, '13641870', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('FERNANDEZ ANGEL', NULL, '16310014', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('BRACAMONTE GENESIS', NULL, '31428533', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('PEROZA SAMUEL', NULL, '33020891', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('VIERA ROSALINDA', NULL, '12717087', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('NOVIS CANDELARIO', NULL, '9416493', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('OROPEZA LOURDES', NULL, '14312752', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('PALMA MILAGRO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('FERNANDEZ RODRIGO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('ORTIZ ALVARO', NULL, '41634669', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('QUINTERO BARBARA', NULL, '13422890', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('TIRADO YUNIOR', NULL, '26372024', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('MOSQUERA EMILI', NULL, '28285779', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('DIAS VICTOR', NULL, '11537536', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('ARAQUE MARIA', NULL, '28100561', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('RAMIREZ BARBARA', NULL, '18461886', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('BRITO DAVID', NULL, '30678485', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('DAVILA MARLENE', NULL, '19102824', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('GARCIA MARIO', NULL, '5613119', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('RODRIGUEZ FREDY', NULL, '14424783', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('FIGUEIRA FERNANDA', NULL, '81659048', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('PALMA YOSE', NULL, '64488239', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('ANGARITA CARMEN', NULL, '12660680', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('COLINA YOANDRI', NULL, '25872328', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('YAPTISTA YERMIN', NULL, '13948173', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('DIAS SANDRA', NULL, '11638321', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('DE SANTIAGO JUANA', NULL, '11688834', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('OLIVERO ANA', NULL, '4281217', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('MARTINEZ MARLIN', NULL, '10576899', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('GARCIA JUAN', NULL, '17755829', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('MARCANO YENNI', NULL, '10384289', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, 'Triaje', 'data 2.docx;data 3.docx'),
  ('DE ANZOLA MANUELA', NULL, '296723', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, 'Nombre alternativo en fuente: D ANZOLA MANUELA', 'data 2.docx;data 3.docx'),
  ('SOJA ALEJANDRA', NULL, '6904629', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('YEGUE EIBAN', NULL, '24058780', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('BERNAL MARCELA', NULL, '6049995', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('AZOCAR VALERIA', NULL, '28544619', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('MORILLO ANABELA', NULL, '34588981', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('MORALES LESVIA', NULL, '29565096', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('BUENO MERIDO', NULL, '17158021', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('MONTOLLA MARIA', NULL, '25025734', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('RIVERO MARLEIDI', NULL, '36091784', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('TORRES ISABEL', NULL, '4718019', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('LOPEZ DUFAR', NULL, '12115323', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('ACOSTA YANELI', NULL, '31760907', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('CHAVEZ NERI', NULL, '81462470', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('CHACON ELIZABETH', NULL, '2734286', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('GONZALEZ ELIZABETH', NULL, '17709218', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('SUCRE PETNA', NULL, '2945823', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, 'traumachk', 'data 2.docx;data 3.docx'),
  ('PAREDES CRUZENDIDA', NULL, '6405488', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, 'Nombre alternativo en fuente: PAREDES CENEIDA', 'data 2.docx;data 3.docx'),
  ('IDAGO ELIANNI', NULL, '32976229', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('BASTIDO VERONICA', NULL, '30170626', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('GONZALEZ ISABEL', NULL, '29701695', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('LOPEZ FRANLEYDI', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('ESTABILITO ANICAR', NULL, '23241059', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('NAVAS YODALIS', NULL, '30072743', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('GONZALEZ ADRIANA', NULL, '82230906', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('MARTINEZ GABRIEL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('MARTINEZ ZORAIDA', NULL, '6092167', NULL, NULL, NULL, NULL, NULL, NULL, 'Hospital Pérez Carreño', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('RAMÍREZ ELEYSA', NULL, NULL, NULL, 64, NULL, NULL, NULL, NULL, 'Cruz Roja', NULL, 'Edif Carabobo', NULL, 'data 2.docx;data 3.docx'),
  ('RODRÍGUEZ MARBELIS', NULL, NULL, NULL, 52, NULL, NULL, NULL, NULL, 'Cruz Roja', NULL, 'Av Lecuna', NULL, 'data 2.docx;data 3.docx'),
  ('RODRÍGUEZ YALITZA', NULL, NULL, NULL, 57, NULL, NULL, NULL, NULL, 'Cruz Roja', NULL, 'Av Lecuna', NULL, 'data 2.docx;data 3.docx'),
  ('ZHANGYOU CHEN', NULL, NULL, NULL, 57, NULL, NULL, NULL, NULL, 'Cruz Roja', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('CHEN BOYE', NULL, NULL, NULL, 21, NULL, NULL, NULL, NULL, 'Cruz Roja', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('FRANCO ANTONIO', NULL, NULL, NULL, 63, NULL, NULL, NULL, NULL, 'Cruz Roja', NULL, 'Av Fuerzas Armadas', NULL, 'data 2.docx;data 3.docx'),
  ('BARRETO IRAMA', NULL, NULL, NULL, 74, NULL, NULL, NULL, NULL, 'Cruz Roja', NULL, 'La Candelaria', NULL, 'data 2.docx;data 3.docx'),
  ('MOISES (MENOR)', NULL, NULL, NULL, 5, NULL, NULL, NULL, NULL, 'Cruz Roja', NULL, 'La Candelaria', NULL, 'data 2.docx;data 3.docx'),
  ('PÉREZ CECALIO', NULL, NULL, NULL, 72, NULL, NULL, NULL, NULL, 'Cruz Roja', NULL, 'La Candelaria', NULL, 'data 2.docx;data 3.docx'),
  ('MOY MARIA', NULL, NULL, NULL, 47, NULL, NULL, NULL, NULL, 'Cruz Roja', NULL, 'La Candelaria', NULL, 'data 2.docx;data 3.docx'),
  ('PÉREZ CARMEN', NULL, NULL, NULL, 64, NULL, NULL, NULL, NULL, 'Cruz Roja', NULL, 'La Candelaria', NULL, 'data 2.docx;data 3.docx'),
  ('OMAÑA RAIZA', NULL, NULL, NULL, 45, NULL, NULL, NULL, NULL, 'Cruz Roja', NULL, 'La Candelaria', NULL, 'data 2.docx;data 3.docx'),
  ('BELANDRIA JOFFRE', NULL, NULL, NULL, 63, NULL, NULL, NULL, NULL, 'Cruz Roja', NULL, 'Valles del Tuy', NULL, 'data 2.docx;data 3.docx'),
  ('BEGOCHEA REINALDO', NULL, NULL, NULL, 43, NULL, NULL, NULL, NULL, 'Cruz Roja', NULL, 'Sarria', NULL, 'data 2.docx;data 3.docx'),
  ('MACHADO CARMEN', NULL, NULL, NULL, 77, NULL, NULL, NULL, NULL, 'Cruz Roja', NULL, 'La Candelaria', NULL, 'data 2.docx;data 3.docx'),
  ('HERNÁNDEZ JACKELINE', NULL, NULL, NULL, 62, NULL, NULL, NULL, NULL, 'Cruz Roja', NULL, 'Misión Vivienda', NULL, 'data 2.docx;data 3.docx'),
  ('TINGY JOSÉ', NULL, NULL, NULL, 44, NULL, NULL, NULL, NULL, 'Cruz Roja', NULL, 'La Candelaria', NULL, 'data 2.docx;data 3.docx'),
  ('MUÑOZ CAMILA', NULL, NULL, NULL, 15, NULL, NULL, NULL, NULL, 'Cruz Roja', NULL, 'Santa Monica', NULL, 'data 2.docx;data 3.docx'),
  ('LLORET LAURA', NULL, NULL, NULL, 85, NULL, NULL, NULL, NULL, 'Cruz Roja', NULL, 'La Candelaria', NULL, 'data 2.docx;data 3.docx'),
  ('LLORET LILIANA', NULL, NULL, NULL, 59, NULL, NULL, NULL, NULL, 'Cruz Roja', NULL, 'La Candelaria', NULL, 'data 2.docx;data 3.docx'),
  ('CEDEÑO CARLOS', NULL, NULL, NULL, 76, NULL, NULL, NULL, NULL, 'Cruz Roja', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('VARELA ANGEL', NULL, NULL, NULL, 47, NULL, NULL, NULL, NULL, 'Cruz Roja', NULL, 'Sarria', NULL, 'data 2.docx;data 3.docx'),
  ('ARTEAGA BETI', NULL, '12067370', NULL, 51, NULL, NULL, NULL, NULL, 'Cruz Roja', NULL, 'La Candelaria', NULL, 'data 2.docx;data 3.docx'),
  ('GUERRA PETRA', NULL, '4806707', NULL, 72, NULL, NULL, NULL, NULL, 'Cruz Roja', NULL, 'La Candelaria', NULL, 'data 2.docx;data 3.docx'),
  ('GARCÍA ANTONIO', NULL, '20101410', NULL, 36, NULL, NULL, NULL, NULL, 'Cruz Roja', NULL, 'Barinas', NULL, 'data 2.docx;data 3.docx'),
  ('ALVARADO NAIROBIS', NULL, '22262602', NULL, 32, NULL, NULL, NULL, NULL, 'Cruz Roja', NULL, 'Barquisimeto', NULL, 'data 2.docx;data 3.docx'),
  ('QUERALES ALEIDA', NULL, '99289918', NULL, 64, NULL, NULL, NULL, NULL, 'Cruz Roja', NULL, 'La Guaira', NULL, 'data 2.docx;data 3.docx'),
  ('CASTILLO JORGE', NULL, NULL, NULL, 26, NULL, NULL, NULL, NULL, 'Periférico de Catia', NULL, NULL, 'Nuevo ingreso / Hermano / Caída 2:16', 'data 2.docx;data 3.docx'),
  ('SÁNCHEZ MARIA', NULL, NULL, NULL, 77, NULL, NULL, NULL, NULL, 'Periférico de Catia', NULL, NULL, 'Traumatismo Ext/Desblo / Sola / Caída 2:19', 'data 2.docx;data 3.docx'),
  ('RODRÍGUEZ CINDY', NULL, NULL, NULL, 30, NULL, NULL, NULL, NULL, 'Periférico de Catia', NULL, NULL, 'Fr reg golpe maxilo / Sola / Caída 2:19', 'data 2.docx;data 3.docx'),
  ('PABÓN MARIANGEL', NULL, NULL, NULL, 21, NULL, NULL, NULL, NULL, 'Periférico de Catia', NULL, NULL, 'Traumatis. encéfalo leve / Mamá / Caída 2:20', 'data 2.docx;data 3.docx'),
  ('COLMENARAS YADHER', NULL, NULL, NULL, 3, NULL, NULL, NULL, NULL, 'Periférico de Catia', NULL, NULL, 'QVOg e. lacera Scap / Mamá / Caída 2:30', 'data 2.docx;data 3.docx'),
  ('MARY DURÓN', NULL, NULL, NULL, 36, NULL, NULL, NULL, NULL, 'Periférico de Catia', NULL, NULL, 'Ciudad lumba torácica / Sola / Caída 2:36', 'data 2.docx;data 3.docx'),
  ('CONTRERAS VALERIA', NULL, NULL, NULL, 18, NULL, NULL, NULL, NULL, 'Periférico de Catia', NULL, NULL, 'Her. cortada / Sola / Acc Moto 2:50 | Nombre alternativo en fuente: VALERIA CONTRERAS', 'data 2.docx;data 3.docx'),
  ('MORENO YADER', NULL, NULL, NULL, 24, NULL, NULL, NULL, NULL, 'Periférico de Catia', NULL, NULL, 'B/edemat guiñat morita / Mamá / Caída 2:56', 'data 2.docx;data 3.docx'),
  ('ESPINOSA FERMÍNE', NULL, NULL, NULL, 70, NULL, NULL, NULL, NULL, 'Periférico de Catia', NULL, 'Amador Cura Iza Macarao', 'Traumate. Elbon + muscular / Hija / Caída 3:00 | Nombre alternativo en fuente: FERMÍNE ESPINOSA', 'data 2.docx;data 3.docx'),
  ('CAPELLA HAROLD', NULL, NULL, NULL, 33, NULL, NULL, NULL, NULL, 'Periférico de Catia', NULL, NULL, 'Traumat. odf con lacera / Sola / Consulta 3:21 | Nombre alternativo en fuente: HAROLD CAPELLA', 'data 2.docx;data 3.docx'),
  ('VALENCIA ELIX', NULL, NULL, NULL, 43, NULL, NULL, NULL, NULL, 'Periférico de Catia', NULL, NULL, 'Traumat. facial + Trauma temporal / Sola / Patín 3:25', 'data 2.docx;data 3.docx'),
  ('RODRÍGUEZ SANELLY', NULL, NULL, NULL, 12, NULL, NULL, NULL, NULL, 'Periférico de Catia', NULL, NULL, 'Contusion h. guaro / Sola / Consulta 3:46', 'data 2.docx;data 3.docx'),
  ('MAYOR HENDERSON', NULL, NULL, NULL, 15, NULL, NULL, NULL, NULL, 'Periférico de Catia', NULL, NULL, 'Les. puncta de ante #18 / Mamá / Caída 3:47', 'data 2.docx;data 3.docx'),
  ('LÓPEZ MARIOLY', NULL, NULL, NULL, 44, NULL, NULL, NULL, NULL, 'Periférico de Catia', NULL, NULL, 'Fractura de propina / Sola / Golpe 3:50', 'data 2.docx;data 3.docx'),
  ('HADDAN YALEISY', NULL, NULL, NULL, 41, NULL, NULL, NULL, NULL, 'Periférico de Catia', NULL, 'Campo Js. Vi Gallego', 'Cassila para / Sola / Caída 4:10 | Nombre alternativo en fuente: YALEISY HADDAN', 'data 2.docx;data 3.docx'),
  ('ALBINO WALTER', NULL, NULL, NULL, 45, NULL, NULL, NULL, NULL, 'Periférico de Catia', NULL, NULL, 'Prosganda abdominal / Sola / Acc Moto 4:15', 'data 2.docx;data 3.docx'),
  ('GONZÁLEZ ANDERSON', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Periférico de Catia', NULL, NULL, 'Fx/edem. de la ulna alt. izq. 5:11', 'data 2.docx;data 3.docx'),
  ('LAMA DANIELA', NULL, NULL, NULL, 3, NULL, NULL, NULL, NULL, 'Periférico de Catia', NULL, '3er plan de la Selva', 'Hijo / Caída 6:57', 'data 2.docx;data 3.docx'),
  ('HERLANE LÓPEZ', NULL, NULL, NULL, 68, NULL, NULL, NULL, NULL, 'Periférico de Catia', NULL, NULL, 'Fío / Caída 6:58', 'data 2.docx;data 3.docx'),
  ('LÓPEZ NEIBOY', NULL, NULL, NULL, 22, NULL, NULL, NULL, NULL, 'Periférico de Catia', NULL, 'Pio Caído', 'Esposa / Caída 7:04', 'data 2.docx;data 3.docx'),
  ('CIPRIOTA SEVILLE', NULL, NULL, NULL, 29, NULL, NULL, NULL, NULL, 'Periférico de Catia', NULL, NULL, 'Esposo / Caída 7:07', 'data 2.docx;data 3.docx'),
  ('QUETOY YSABEL', NULL, NULL, NULL, 36, NULL, NULL, NULL, NULL, 'Periférico de Catia', NULL, NULL, 'Esposa / Her. cuta 8l / Caída 7:14', 'data 2.docx;data 3.docx'),
  ('PASTONO GYAMILY', NULL, NULL, NULL, 32, NULL, NULL, NULL, NULL, 'Periférico de Catia', NULL, 'Escalipto San Blas', 'Papá / Caída 7:20', 'data 2.docx;data 3.docx'),
  ('RODRÍGUEZ PINDIOLE', NULL, NULL, NULL, 51, NULL, NULL, NULL, NULL, 'Periférico de Catia', NULL, 'Calle Principal', 'Sola / Caída 7:28', 'data 2.docx;data 3.docx'),
  ('FRANKLIN ALFONSO', NULL, NULL, NULL, 65, NULL, NULL, NULL, NULL, 'Periférico de Catia', NULL, 'Mosquito de Morolina', 'Sola / Caída 7:28', 'data 2.docx;data 3.docx'),
  ('SALAZAR CAROLINE', NULL, NULL, NULL, 6, NULL, NULL, NULL, NULL, 'Periférico de Catia', NULL, 'Ly/ Guiñare', 'Sobrín / Caída 7:30', 'data 2.docx;data 3.docx'),
  ('MARTÍNEZ YAMILITH', NULL, NULL, NULL, 30, NULL, NULL, NULL, NULL, 'Periférico de Catia', NULL, 'Se. Grativia', 'Amiga / Caída 7:46', 'data 2.docx;data 3.docx'),
  ('RIVAS MARY', NULL, NULL, NULL, 30, NULL, NULL, NULL, NULL, 'Periférico de Catia', NULL, 'La Cortada de Calle', 'Esposa / Caída 7:50', 'data 2.docx;data 3.docx'),
  ('PENA YOHSEN', NULL, NULL, NULL, 51, NULL, NULL, NULL, NULL, 'Periférico de Catia', NULL, 'Magallanes', 'Solo / Caída 7:56', 'data 2.docx;data 3.docx'),
  ('ZEALARIO ALEXIS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Periférico de Catia', NULL, 'Carabilla + Sector Río', NULL, 'data 2.docx;data 3.docx'),
  ('GONZÁLEZ ANA', NULL, NULL, NULL, 46, NULL, NULL, NULL, NULL, 'Periférico de Catia', NULL, 'Calle San Isidro', 'Caída', 'data 2.docx;data 3.docx'),
  ('ENDER RANGEL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Periférico de Catia', NULL, 'por Suere', 'Hermanos / Caída', 'data 2.docx;data 3.docx'),
  ('YACHER NANCY DURÁN', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Periférico de Catia', NULL, 'Ciudad Nueva Torre', NULL, 'data 2.docx;data 3.docx'),
  ('YARLYS CONTRERAS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Periférico de Catia', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('ALEX PALENCIA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Periférico de Catia', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('DANELY RODRÍGUEZ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Periférico de Catia', NULL, 'Los Paraísos de #13', NULL, 'data 2.docx;data 3.docx'),
  ('HELINSSON AQUINO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Periférico de Catia', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('GORDOFÓN GONZALEZ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Periférico de Catia', NULL, NULL, NULL, 'data 2.docx;data 3.docx'),
  ('CERVELAN FERMÍNE', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Periférico de Catia', NULL, NULL, NULL, 'data 2.docx;data 3.docx');

COMMIT;
